# Manual workflow to release new package version
name: Manual-Version-Release

on:
  workflow_dispatch:
    inputs:
      changeLog:
        description: 'Change Log'
        required: true
        default: ''
      releaseType:
        type: choice
        description: Select major/minor/patch
        options:
        - major
        - minor
        - patch
         
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:      
      - run: echo 'Starting the workflow'

      - uses: oprypin/find-latest-tag@v1
        id: get-latest-tag
        with:
          repository: unstoppabledomains/resolution-go
          releases-only: false

      - name: 'Get next versions'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.get-latest-tag.outputs.tag }}
     
      - name: Set new tag
        id: set-new-tag
        run: |
          if [[ ${{ github.event.inputs.releaseType }} == major ]]; then
            echo "tag=${{ steps.semvers.outputs.v_major }}" >> $GITHUB_OUTPUT
          elif [[ ${{ github.event.inputs.releaseType }} == minor ]]; then
            echo "tag=${{ steps.semvers.outputs.v_minor }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ steps.semvers.outputs.v_patch }}" >> $GITHUB_OUTPUT
          fi
      - name: 'Log inputs'
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.get-latest-tag.outputs.tag }}
          echo ${{ steps.set-new-tag.outputs.tag }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Create tag'
        run: |
          git tag ${{ steps.set-new-tag.outputs.tag }}
          git push origin --tags
    
      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ steps.set-new-tag.outputs.tag }}
          release-notes: ${{ github.event.inputs.changeLog }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.event.release.target_commitish }}
          commit_message: Release new version ${{ steps.set-new-tag.outputs.tag }}
          file_pattern: CHANGELOG.md